### ISSUE TITLE
Add support for windows

### ISSUE THREAD

**Issue by ShounenArgha** [Jothin-kumar/time-widget#1]
**Describe the bug**
It looks like, windows is not supported... Add support for windows!
**Additional context**
This error occurs...
![image](https://user-images.githubusercontent.com/78955676/141140920-61657a58-4bda-4317-9bc1-9e907cc8e620.png)

**Comment by Jothin-kumar** [comment]
What os are u in @Arghadatta

**Comment by Jothin-kumar** [comment]
@Arghadatta, I think it is because, u are on windows! It currently supports only Linux! Let me edit this issue as "Add support for windows"

**Comment by ShounenArgha** [comment]
> What os are u in @Arghadatta

OS:Windows 7 Ultimate(SP1)64bit

**Comment by ShounenArgha** [comment]
> @Arghadatta, I think it is because, u are on windows! It currently supports only Linux! Let me edit this issue as "Add support for windows"

Oh,sorry for bothering!
thanks

**Comment by Jothin-kumar** [comment]
@Arghadatta, Now you can use this on windows too!
